/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dafuzz

import dafuzz.generator.Generator
import dafuzz.validator.OutputValidator
import kotlinx.coroutines.runBlocking

class Main {
    private val generator = Generator()
    private val validator = OutputValidator()

    fun fuzz() = runBlocking {
        validator.validateFile("output", "hello")
    }
}

fun main() {
    println(Main().fuzz())
}
